cinematica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('api/trending-movies/', views.trending_movies_api, name='trending_movies_api'),  
    path('login/', views.login_user, name='login'),  
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('preferences/', views.movie_preferences, name='preferences'),
    path('preferences/data', views.user_preference_data, name='preferences_data'),
    path('about/', views.about, name='about'),
    path('overview/<int:movie_id>/', views.movie_overview, name='overview'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),
    path("submit_reply/", views.submit_reply, name="submit_reply"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

class UserPreference(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    liked_movies = models.JSONField(default=list, blank=True)     # list of liked movie IDs
    disliked_movies = models.JSONField(default=list, blank=True)  # list of disliked movie IDs
    recommended_movies = models.JSONField(default=list, blank=True)  # list of recommended movie IDs

    def __str__(self):
        return f"{self.user.username}'s Preferences"

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie_id = models.IntegerField(null=True, blank=False)  # TMDB ID of the movie
    rating = models.IntegerField(null=True, blank=False, default=0)  # Rating out of 10
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Comment by {self.user.username} on {self.movie_id}" 
    
class Reply(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='replies')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Reply by {self.user.username} to {self.review.user.username}'s comment"

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Review, UserPreference, User, Reply
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .rec import fetch_recommendations
import json
from datetime import datetime
from django.contrib.auth.decorators import login_required
import requests
from .utils import fetch_trending_movies


@csrf_exempt
def home(request):
    """
    For the home page:
      - If GET: just render the home.html template.
      - If POST: user clicked Like/Dislike on a movie card, so update their UserPreference.liked_movies or .disliked_movies,
        recommendations, save, and return the same page.
    """    
    if not request.user.is_authenticated:
        return redirect("core:login")
    
    if request.method == "POST":
        data = json.loads(request.body)
        user_pref = UserPreference.objects.get(user=request.user)
        if data.get("liked"):
            user_pref.liked_movies.append({
                "id": int(data.get("id")),
            })
        else:
            user_pref = UserPreference.objects.get(user=request.user)
            user_pref.disliked_movies.append({
                "id": int(data.get("id")),
            })
            
        # Remove the movie from the opposite list if present
        movie_id = int(data.get("id"))
        if data.get("liked"):
            user_pref.disliked_movies = [m for m in user_pref.disliked_movies if m.get("id") != movie_id]
        else:
            user_pref.liked_movies = [m for m in user_pref.liked_movies if m.get("id") != movie_id]
        
        user_pref.save()
        recommended_movies = fetch_recommendations([movie["id"] for movie in user_pref.liked_movies], [movie["id"] for movie in user_pref.disliked_movies])
        user_pref.recommended_movies = recommended_movies
        user_pref.save()
    
    return render(request, "pages/home.html", {
        "trending": fetch_trending_movies(),
        "genres": [
            {"id": 28, "name": "Action"},
            {"id": 12, "name": "Adventure"},
            {"id": 16, "name": "Animation"},
            {"id": 35, "name": "Comedy"},
            {"id": 80, "name": "Crime"},
            {"id": 99, "name": "Documentary"},
            {"id": 18, "name": "Drama"},
            {"id": 10751, "name": "Family"},
            {"id": 14, "name": "Fantasy"},
            {"id": 36, "name": "History"},
            {"id": 27, "name": "Horror"},
            {"id": 10402, "name": "Music"},
            {"id": 9648, "name": "Mystery"},
            {"id": 10749, "name": "Romance"},
            {"id": 878, "name": "Science Fiction"},
            {"id": 10770, "name": "TV Movie"},
            {"id": 53, "name": "Thriller"},
            {"id": 10752, "name": "War"},
            {"id": 37, "name": "Western"}
        ]
    })

def login_user(request):  
    """
    The login page:
      - If already authenticated, redirect to home.
      - On POST attempt Django auth, on success redirect home, if it fails then errors happen.
    """
    if request.user.is_authenticated:
        return redirect("core:home")
    
    if request.method == "POST":
        username = request.POST.get("username")  
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("core:home") 
        else:
            return render(request, "auth/login.html", {"error": "Invalid credentials"})
    
    return render(request, "auth/login.html") 

def register_user(request):
    """
    Registration page:
      - If already logged in send to home
      - On POST validate password match and unique username, create User + UserPreference, log them in, redirect home.
    """
    if request.user.is_authenticated:
        return redirect("core:home")
    
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password_confirm = request.POST.get("password2")
        
        if password == password_confirm:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already exists")
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                user_pref = UserPreference(user=user)
                user_pref.save()
                login(request, user)
                return redirect("core:home")
        else:
            return render(request, "auth/register.html", {"error": "Passwords do not match"})
    
    return render(request, "auth/register.html")

def logout_user(request):  
    logout(request)
    return redirect("core:login")  

@csrf_exempt
def movie_preferences(request):
    """
    Movie Preferences page:
      - On GET render the form template (letting JS fetch years or movies).
      - On POST receive liked/disliked arrays, compute recommendations, save them all, then redirect to home so JS can pull them.
    """
    if not request.user.is_authenticated:
        return redirect("core:login")
    
    if request.method == "POST":
        data = json.loads(request.body)
        liked_movies = []
        disliked_movies = []
        for movie in data.get("movies")["liked"]:
            liked_movies.append({
                "id": movie,
            })
        
        for movie in data.get("movies")["disliked"]:
            disliked_movies.append({
                "id": movie,
            })    
    
        recommended_movies = fetch_recommendations([movie["id"] for movie in liked_movies], [movie["id"] for movie in disliked_movies])
            
        user_pref = UserPreference.objects.get(user=request.user)
        user_pref.liked_movies = liked_movies
        user_pref.disliked_movies = disliked_movies
        user_pref.recommended_movies = recommended_movies
        user_pref.save()
        
        return redirect("core:home")
    
    current_year = datetime.now().year
    all_years = list(range(current_year, 1899, -1))
    
    return render(request, "pages/preferences.html", {"years": all_years})

def user_preference_data(request):
    """
    JSON endpoint for the front-end JS:
      returns { liked: [...], disliked: [...], recommended: [...] } so the movie-cards JS can render them.
    """
    user_pref = UserPreference.objects.get(user=request.user)
    
    if request.method == "GET":
        return JsonResponse({
            "liked": user_pref.liked_movies,
            "disliked": user_pref.disliked_movies,
            "recommended": user_pref.recommended_movies,
        })
    
    return JsonResponse({
        "liked": user_pref.liked_movies,
        "disliked": user_pref.disliked_movies,
        "recommended": user_pref.recommended
    })

def about(request):
    if not request.user.is_authenticated:
        return redirect("core:login")
    
    return render(request, "pages/about.html")

def movie_overview(request, movie_id):
    """
    Display the movie details page:
      - Fetches the movie info + credits from TMDB
      - Fetches embedded YouTube trailer (if any)
      - Loads all reviews + nested replies from our database
      - Calculates an average local rating
      - Renders the overview template with that data
    """
    api_key = '595786e6aaaa7490b57f9936a7ae819f'
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&append_to_response=credits"

    response = requests.get(url)
    if response.status_code != 200:
        return render(request, 'overview.html', {'movie': None})

    data = response.json()

    #fetch the YouTube videos for trailers
    trailer_url = None
    video_url = f"https://api.themoviedb.org/3/movie/{movie_id}/videos?api_key={api_key}"
    video_response = requests.get(video_url)
    if video_response.status_code == 200:
        videos = video_response.json().get('results', [])
        for video in videos:
            if video['type'] == 'Trailer' and video['site'] == 'YouTube':
                trailer_url = f"https://www.youtube.com/embed/{video['key']}"
                break

    # fetch the movie providers where the movies are available to watch
    provider_url = f"https://api.themoviedb.org/3/movie/{movie_id}/watch/providers?api_key={api_key}"
    provider_response = requests.get(provider_url)
    PROVIDER_URLS = {
        8: "https://www.netflix.com",         # Netflix
        10: "https://www.amazon.com/video",    # Amazon Video
        15: "https://www.hulu.com",          # Hulu
        337: "https://www.disneyplus.com",    # Disney+
        384: "https://www.hbomax.com",         
        2: "https://www.apple.com/apple-tv-plus/",  
        3: "https://play.google.com/store/movies?hl=en_US",  
        192: "https://www.youtube.com/feed/storefront",
        68: "https://www.microsoft.com/en-us/store/movies-and-tv",
        257: "http://fubo.tv/stream/ca/fubo-movie-network/",
        384: "https://www.max.com/",
        73: "https://tubitv.com/",
        524: "https://www.discoveryplus.com/",
        118: "https://www.hbo.com/",
        538: "https://www.plex.tv/",
    }
    providers = []

    provider_link = None

    if provider_response.status_code == 200:
        provider_data = provider_response.json().get("results", {})
        us_data = provider_data.get("US", {}) # providers available in the US

        provider_link = us_data.get("link")  # Base link to watch the movie

        provider_sections = ["flatrate", "rent", "buy", "ads", "free"] # all type of providers

        # make sure to not display duplicate providers
        seen = set()
        for section in provider_sections:
            for p in us_data.get(section, []):
                pid = p["provider_id"]
                if pid not in seen:

core/templates/pages/about.html
{% extends "page.html" %}
{% load static %}

{% block title %} Cinematica | About {% endblock %}

{% block main_content %}
    <section id="team">
        <h2>Meet Our Team</h2>
        <div class="team-members">
            <div class="team-member">
                <img src="{% static 'images/team/andria.jpg' %}" alt="Team Member 1" class="team-photo">
                <h3>Andria Beridze</h3>
                <p>Product Manager</p>
            </div>
            <div class="team-member">
                <img src="{% static 'images/team/brendon.jpg' %}" alt="Team Member 2" class="team-photo">
                <h3>Brendon Mani</h3>
                <p>Data Manager</p>
            </div>
            <div class="team-member">
                <img src="{% static 'images/team/beckham.jpg' %}" alt="Team Member 3" class="team-photo">
                <h3>Beckham Truong</h3>
                <p>Backend Developer</p>
            </div>
            <div class="team-member">
                <img src="{% static 'images/team/shahab.jpg' %}" alt="Team Member 4" class="team-photo">
                <h3>Shahab Din</h3>
                <p>Frontend Developer</p>
            </div>
        </div>
    </section>

    <section id="brief" style="max-width: 900px; margin: 0 auto; padding: 20px;">
        <h2 style="text-align: center;">About Our Site</h2>
        <p style="text-align: center;">Welcome to Cinematica, your go-to platform for discovering and recommending movies based on your unique preferences. By integrating the vast IMDb movie database, we allow users to explore movies, select genres they enjoy, and receive personalized recommendations. Whether you're looking for a movie similar to your favorite or just need fresh ideas for your next binge, Cinematica is here to help you find your next great movie experience.</p>
        
        <h3 style="text-align: center;">Our Mission</h3>
        <p style="text-align: center;">Our mission is to enhance movie discovery by offering personalized, data-driven recommendations tailored to each user's taste. We aim to make movie watching more exciting and convenient by providing users with accurate suggestions based on their preferences, ensuring they never run out of options to explore.</p>

        <h3 style="text-align: center;">Our Core Values</h3>
        <ul style="text-align: center;">
            <li><strong>Personalization:</strong> We believe every movie lover is unique, and we tailor our recommendations to reflect individual tastes and preferences.</li>
            <li><strong>Innovation:</strong> We are committed to using the latest technologies and data to provide the most accurate and engaging movie suggestions possible.</li>
            <li><strong>Accessibility:</strong> We aim to make movie discovery easy for everyone, regardless of their movie knowledge or experience.</li>
            <li><strong>Entertainment:</strong> Above all, we are passionate about creating enjoyable and satisfying experiences for movie enthusiasts of all kinds.</li>
        </ul>
    </section>
{% endblock %}

core/templates/pages/home.html
{% extends "page.html" %}
{% load static %}

{% block title %} Cinematica | Home {% endblock %}

{% block main_content %}
    <div class="page-title">
        <h1>Trending Movies</h1>
        <hr>
    </div>
    <div class="trending-movies" id="trending">
        <div class="control-btns">  
            <button class="control prev" id="prev"><i class="bi bi-caret-left-fill"></i></button>
            <button class="control next" id="next"><i class="bi bi-caret-right-fill"></i></button>
        </div>
        <div class="indicators-container">
            {% for movie in trending %}
                <i class="bi bi-circle" id="ind-{{ forloop.counter }}"></i>
            {% endfor %}
        </div>
        {% for movie in trending %}
            <div class="movie-card-lg" id="movie"> 
                <img src="https://image.tmdb.org/t/p/original/{{ movie.backdrop_path }}" alt="{{ movie.title }}" class="movie-poster">
                <div class="gradient"></div>
                <div class="movie-info">
                    <h2 class="movie-title">{{ movie.title }}</h2>
                    <p class="movie-genres">
                        {% for genre in genres %}
                            {% for id in movie.genre_ids %}
                                {% if genre.id == id %}
                                    {{ genre.name }}{% if not forloop.last %} &#9679; {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </p>

                    <a href="/overview/{{ movie.id }}"><button class="btn">More Info</button></a>
                </div>
            </div>
        {% endfor %}
    </div>   

    <div class="page-title">
        <h1>Recommended for You</h1>
        <hr>
    </div>
    <div class="filter" id="filter">
        <input type="text" id="search" placeholder="Search for a movie...">
    </div>
    <div class="container recommended-movies" id="recommended">

    </div>
    <script src="{% static 'js/recommended.js' %}"></script>   
{% endblock %}

core/templates/pages/overview.html
{% extends "page.html" %}
{% load static %}

{% block title %}
    {{ movie.title }} – Movie Overview
{% endblock %}

{% block main_content %}
    <div class="container overview">
        <section class="movie-overview">
            <div class="poster-container">
                <img src="{{ movie.poster_url }}" alt="{{ movie.title }} Poster" class="poster">
            </div>
            <div class="movie-details">
                <div class="brief-description" style="display: flex; align-items: center; gap: 1rem;">
                    <h1 style="margin: 0;">
                        {{ movie.title }}
                        (<span style="color: var(--primary);">{{ movie.release_year }}</span>)
                    </h1>
                    <!-- Like/Dislike buttons -->
                    {% if movie.preference == "liked" %}
                        <span class="message liked">Liked <i class="bi bi-hand-thumbs-up-fill"></i></span>
                        <button type="button" class="opt dislike" id="{{ movie.id }}" style="height: 2rem; width: 2rem;"><i class="bi bi-hand-thumbs-down-fill"></i></button>
                    {% elif movie.preference == "disliked" %}
                        <button type="button" class="opt like" id="{{ movie.id }}" style="height: 2rem; width: 2rem;"><i class="bi bi-hand-thumbs-up-fill"></i></button>
                        <span class="message disliked">Disliked <i class="bi bi-hand-thumbs-down-fill"></i></span>
                    {% else %}
                        <button type="button" class="opt like" id="{{ movie.id }}" style="height: 2rem; width: 2rem;"><i class="bi bi-hand-thumbs-up-fill"></i></button>
                        <button type="button" class="opt dislike" id="{{ movie.id }}" style="height: 2rem; width: 2rem;"><i class="bi bi-hand-thumbs-down-fill"></i></button>
                    {% endif %}
                </div>
                <p>{{ movie.release_date }} &#9679; {{ movie.single_genre }} &#9679; {{ movie.duration }}</p>

                <div class="score-container">
                    <div class="score">
                        <div class="rating-indicator" id="indicator">{{ movie.global_rating }}%</div>
                        <span>Global Score</span>
                    </div>
                    <div class="score">
                        <div class="rating-indicator" id="indicator">{{ movie.local_rating }}</div>
                        <span>Local Score</span>
                    </div>
                </div>

                <div class="description">
                    <h2>Description</h2>
                    <p>{{ movie.description }}</p>
                </div>

                <div class="trailer-button">
                    {% if movie.trailer_url %}
                        <button class="btn trailer-btn" onclick="playTrailer()">Watch Trailer</button>
                        <button class="btn stop-btn" onclick="stopTrailer()" style="display: none;">Hide Trailer</button>
                    {% endif %}
                </div>

                <div id="trailer-container" style="display: none; margin-top: 20px;">
                    <iframe width="560" height="315"
                        src="{{ movie.trailer_url }}"
                        title="YouTube trailer" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowfullscreen>
                    </iframe>
                </div>

                {% if movie.providers %}
                    <div id="provider-logos" class="provider-logos">
                        <h4>Available On:</h4>
                        {% for provider in movie.providers %}
                            <div class="provider {% if forloop.counter > 5 %}hidden-provider{% endif %}">
                                <a href="{{ provider.link }}" target="_blank" rel="noopener">
                                    <img
                                      src="https://image.tmdb.org/t/p/w45{{ provider.logo_path }}"
                                      alt="{{ provider.provider_name }}"
                                      title="{{ provider.provider_name }}">
                                </a>
                            </div>
                        {% endfor %}
                        {% if movie.providers|length > 5 %}
                            <button id="show-all-btn" class="show-all-btn btn">Show All</button>
                        {% endif %}
                    </div>
                {% else %}
                    <h4>No streaming providers available.</h4>
                {% endif %}

                <div class="people">
                    <span>Director:</span> {{ movie.director }}<br>
                    <span>Cast:</span> {{ movie.actors }}
                </div>
            </div>
        </section>

        <hr>

        <section class="user-reviews">
            <h3>Leave a Review</h3>
            <form action="{% url 'core:submit_comment' %}" method="post" id="comment-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="rating">Rating:</label>
                    <span>
                        <input type="number" name="rating" id="rating" min="1" max="10" required> / 10
                    </span>
                </div>
                <input type="hidden" name="movie_id" value="{{ movie.id }}">
                <div class="form-group">
                    <textarea name="comment" id="comment" rows="4" placeholder="Write your thoughts here..." required></textarea>
                </div>
                <button type="submit" class="btn btn-primary mt-2">Submit Comment</button>
            </form>

            <hr>

            <div class="existing-comments">
                <h3>Past Reviews</h3>
                <ul class="list-group">
                    {% for review in movie.reviews %}
                        <li class="list-group-item review">
                            <div class="about-user">
                                <span class="user">{{ review.user }}</span>
                                <span class="rating-indicator">{{ review.rating }} / 10</span>
                                <span class="created_at">{{ review.created_at }}</span>
                            </div>

                            <hr>

                            <div class="content">
                                <p>{{ review.text }}</p>
                            </div>

                            <form action="{% url 'core:submit_reply' %}"
                                  method="post"
                                  class="reply-form"
                                  style="margin-top: 5px;">
                                {% csrf_token %}
                                <input type="hidden" name="review_id" value="{{ review.id }}">
                                <input type="hidden" name="movie_id" value="{{ movie.id }}">
                                <div class="form-group" style="margin-bottom: .5rem;">
                                    <label for="reply-{{ review.id }}">Your Reply:</label>
                                    <textarea name="comment"
                                              id="reply-{{ review.id }}"
                                              rows="1"
                                              style="height: 5rem; line-height: 1.2;"
                                              placeholder="Write your reply..."
                                              required></textarea>
                                </div>
                                <button type="submit"
                                        class="btn btn-sm btn-primary mt-1">
                                    Submit Reply
                                </button>
                            </form>

                            {% if review.replies %}
                                <ul class="list-group replies">
                                    {% for reply in review.replies %}
                                        <li class="list-group-item reply">
                                            <div class="about-user" style="margin-bottom: -10px;">
                                                <span class="user">{{ reply.user }}</span>
                                                <span class="created_at">{{ reply.created_at }}</span>
                                            </div>
                                            <hr>
                                            <div class="content">
                                                <p>{{ reply.text }}</p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% empty %}
                        <li class="list-group-item">No comments yet.</li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    </div>
{% endblock %}

{% block extra_js %}
  <script type="module" src="{% static 'js/overview.js' %}"></script>
{% endblock %}

core/templates/pages/preferences.html
{% extends "page.html" %}
{% load static %}

{% block title %} Cinematica | Preferences {% endblock %}

{% block main_content %}
    <div class="page-title">
        <h1>Preferences</h1>
    </div>
    <div class="container preferences">
        <div class="filter" id="filter">
            <input type="text" id="search" placeholder="Search for a movie...">
            <div class="filter-options">
                <div class="filter-option">
                    <label for="genre">Genre</label>
                    <select name="genre" id="genre">
                        <option value="all">All</option>
                        <option value="28">Action</option>
                        <option value="12">Adventure</option>
                        <option value="16">Animation</option>
                        <option value="35">Comedy</option>
                        <option value="80">Crime</option>
                        <option value="18">Drama</option>
                        <option value="14">Fantasy</option>
                        <option value="27">Horror</option>
                        <option value="9648">Mystery</option>
                        <option value="10749">Romance</option>
                        <option value="878">Sci-Fi</option>
                        <option value="53">Thriller</option>
                    </select>
                </div>
                <div class="filter-option">
                    <label for="rating">Rating</label>
                    <select name="rating" id="rating">
                        <option value="all">All</option>
                        <option value="10">10</option>
                        <option value="9">9</option>
                        <option value="8">8</option>
                        <option value="7">7</option>
                        <option value="6">6</option>
                        <option value="5">5</option>
                        <option value="4">4</option>
                        <option value="3">3</option>
                        <option value="2">2</option>
                        <option value="1">1</option>
                    </select>
                </div>
                <div class="filter-option">
                    <label for="year">Year</label>
                    <select name="year" id="year">
                        <option value="all">All</option>
                        {% for year in years %}
                            <option value="{{ year }}">{{ year }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="titles">
            <div class="title all-movies">All Movies</div>
            <div class="title liked">Liked Movies</div>
            <div class="title disliked">Disliked Movies</div>
        </div>
        <div class="sort">
            <div class="container section all-movies" id="all">
                <div class="loading" id="loading" style="
                        background-color: var(--background);
                        position: absolute;
                        top: 0;
                        left: 0;
                        bottom: 0;
                        right: 0;
                        z-index: 5;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                    ">
                    <p>Loading...</p>
                </div>
            </div>
            <div class="container section liked" id="liked">

            </div>
            <div class="container section disliked" id="disliked">

            </div>
        </div>
        <div class="options">
            <div class="btn" onclick="savePreferences()" id="save-preferences">Save</div>
            <a href="{% url 'core:home' %}">Cancel</a>
        </div>
    </div>
{% endblock %}